### PR TITLE
Completed css-three-column-layout. Bryan Valdovinos

### PR DESCRIPTION
**Pull request by bryanvaldovinos**
Screen Shot 2022-05-13 at 12 08 11 AM
Screen Shot 2022-05-11 at 10 14 50 PM

### CODE REVIEW

**Comment by bryanvaldovinos** [comment]
Spent about 2.5 hours trying to get the images to not overflow border-radius... attempted various ways to fix issue, unfortunately could not resolve... sigh

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Bryan! This does not match the example, please revise and submit a new screenshot with your revision.

**Comment by bryanvaldovinos** [comment]
Screen Shot 2022-05-13 at 11 08 54 AM

**Comment by bryanvaldovinos** [comment]
Added screenshot!

**Comment by bryanvaldovinos** [comment]
Screen Shot 2022-05-15 at 7 16 06 PM

**Comment by bryanvaldovinos** [comment]
Went ahead and also fixed class names on this project as well, screenshot updated.

**Review by codingcodymiller — APPROVED** [review]
Nice work!

**Pull request merged**
